CREATE DATABASE IF NOT EXISTS tiempo_app;
USE tiempo_app;

CREATE TABLE IF NOT EXISTS consultas (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CIUDAD VARCHAR(40),
    PAIS VARCHAR(40),
    FECHA DATETIME DEFAULT CURRENT_TIMESTAMP
);